import React, { useState } from 'react';
import {
  Box,
  Grid,
  Card,
  CardContent,
  Typography,
  TextField,
  Button,
  Switch,
  FormControlLabel,
  Chip,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Avatar,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Alert,
  MenuItem,
  Select,
  FormControl,
  InputLabel,
  Container,
  Fade,
  Grow,
  Snackbar,
  Tooltip,
  CircularProgress,
} from '@mui/material';
import {
  Add,
  Edit,
  Delete,
  Search,
  TrendingUp,
  TrendingDown,
  CheckCircle,
  Warning,
  Info,
  School,
  Email,
  Phone,
  CalendarToday,
  Star,
  Refresh,
  Visibility,
  MoreVert,
  Download,
  Upload,
  Assessment,
  Timer,
  Book,
  VideoLibrary,
  Help,
  Person,
  Group,
  Analytics,
  Settings,
  Notifications,
  Dashboard,
  ExpandMore,
  ExpandLess,
  FilterAlt,
  Sort,
  CloudUpload,
  CloudDownload,
  Print,
  Share,
  Favorite,
  FavoriteBorder,
  ThumbUp,
  ThumbDown,
  Grade,
  Work,
  Psychology,
  Science,
  Language,
  MusicNote,
  Sports,
  Computer,
  History,
  Public,
} from '@mui/icons-material';
import { useData } from '../../../contexts/DataContext';
import { useAuth } from '../../../contexts/AuthContext';
import toast from 'react-hot-toast';
import PhoneNumberInput from '../../common/PhoneNumberInput';
import { themeColors } from '../../../theme/adminTheme';
import NotificationIcon from '../../common/NotificationIcon';

interface TeacherManagementProps {
  schoolBranding?: any;
}

const TeacherManagement: React.FC<TeacherManagementProps> = ({ schoolBranding }) => {
  // Helper function to get branding colors
  const getBrandingColors = () => {
    const primaryColor = schoolBranding?.branding?.primaryColor || schoolBranding?.primaryColor || '#667eea';
    const secondaryColor = schoolBranding?.branding?.secondaryColor || schoolBranding?.secondaryColor || '#764ba2';
    return { primaryColor, secondaryColor };
  };

  const { primaryColor, secondaryColor } = getBrandingColors();
  const brandingGradient = `linear-gradient(135deg, ${primaryColor} 0%, ${secondaryColor} 100%)`;
  const brandingGradientHover = `linear-gradient(135deg, ${primaryColor}dd 0%, ${secondaryColor}dd 100%)`;

  const [openTeacherDialog, setOpenTeacherDialog] = useState(false);
  const [openTrainingDialog, setOpenTrainingDialog] = useState(false);
  const [openDeleteDialog, setOpenDeleteDialog] = useState(false);
  const [selectedTeacher, setSelectedTeacher] = useState<any>(null);
  const [dialogType, setDialogType] = useState<'add' | 'edit' | 'view'>('add');
  const [teacherToDelete, setTeacherToDelete] = useState<any>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterGrade, setFilterGrade] = useState('');
  const [filterStatus, setFilterStatus] = useState('');
  const [filterEmailPermission, setFilterEmailPermission] = useState('');
  const [viewMode, setViewMode] = useState<'table' | 'grid'>('table');
  const [expandedTeacher, setExpandedTeacher] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState('name');
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('asc');
  const [showFilters, setShowFilters] = useState(false);
  const [loading, setLoading] = useState(false);

  // State for teacher form
  const [teacherForm, setTeacherForm] = useState({
    name: '',
    email: '',
    phone: '',
    grade: '',
    password: '',
    sendWelcomeEmail: true,
    canEmailReports: false,
    hireDate: '',
    specialization: '',
    qualifications: '',
    bio: '',
    isActive: true,
  });

  const { teachers, students, classes, reports, addTeacher, updateTeacher, deleteTeacher, analytics, school, refreshData, getStudentsByTeacherClasses, getReportsByTeacherStudents } = useData();
  const { user } = useAuth();

  // Function to get the total number of students for a teacher across all their assigned classes
  const getTeacherStudentCount = (teacherId: string) => {
    if (!teacherId || !getStudentsByTeacherClasses) {
      return 0;
    }
    const teacherStudents = getStudentsByTeacherClasses(teacherId);
    console.log(`TeacherManagement - Teacher ${teacherId} has ${teacherStudents.length} students:`, teacherStudents);
    return teacherStudents.length;
  };

  // Function to get the total number of reports generated by a teacher
  const getTeacherReportCount = (teacherId: string) => {
    if (!teacherId || !getReportsByTeacherStudents) {
      return 0;
    }
    const teacherReports = getReportsByTeacherStudents(teacherId);
    console.log(`TeacherManagement - Teacher ${teacherId} has ${teacherReports.length} reports:`, teacherReports);
    return teacherReports.length;
  };

  // Function to calculate average time per report for a teacher
  const getTeacherAvgTimePerReport = (teacherId: string) => {
    if (!teacherId || !getReportsByTeacherStudents) {
      return 0;
    }
    
    const teacherReports = getReportsByTeacherStudents(teacherId);
    if (teacherReports.length === 0) {
      return 0;
    }

    let totalTime = 0;
    let reportsWithTimeData = 0;

    teacherReports.forEach(report => {
      let reportTime = 0;
      
      // Calculate audio recording time
      if (report.voiceRecording) {
        if (report.voiceRecording.recordingDuration) {
          // Convert seconds to minutes
          reportTime += report.voiceRecording.recordingDuration / 60;
        } else if (report.voiceRecording.recordings && report.voiceRecording.recordings.length > 0) {
          // Sum up all recording durations
          const totalRecordingDuration = report.voiceRecording.recordings.reduce((sum, recording) => {
            return sum + (recording.duration || 0);
          }, 0);
          reportTime += totalRecordingDuration / 60; // Convert seconds to minutes
        }
      }

      // Add estimated AI generation time (typically 30-60 seconds)
      // This is an estimate since we don't have exact AI generation time
      const estimatedAIGenerationTime = 0.75; // 45 seconds = 0.75 minutes
      reportTime += estimatedAIGenerationTime;

      // Add estimated review/editing time (typically 2-5 minutes)
      const estimatedReviewTime = 3.5; // 3.5 minutes average
      reportTime += estimatedReviewTime;

      if (reportTime > 0) {
        totalTime += reportTime;
        reportsWithTimeData++;
      }
    });

    // Calculate average time per report
    const avgTime = reportsWithTimeData > 0 ? totalTime / reportsWithTimeData : 0;
    
    console.log(`TeacherManagement - Teacher ${teacherId} avg time per report: ${avgTime.toFixed(1)} minutes (${reportsWithTimeData}/${teacherReports.length} reports with time data)`);
    
    return Math.round(avgTime * 10) / 10; // Round to 1 decimal place
  };

  // Function to calculate teacher efficiency score
  const getTeacherEfficiency = (teacherId: string) => {
    if (!teacherId || !getReportsByTeacherStudents || !getTeacherStudentCount) {
      return 0;
    }
    
    const teacherReports = getReportsByTeacherStudents(teacherId);
    const teacherStudents = getTeacherStudentCount(teacherId);
    
    if (teacherStudents === 0) {
      return 0;
    }

    let efficiencyScore = 0;
    let totalWeight = 0;

    // 1. Report Completion Rate (35% weight) - Reduced from 40% to make room for frequency compliance
    const completionRate = teacherReports.length / teacherStudents;
    const completionScore = Math.min(completionRate * 100, 100); // Cap at 100%
    efficiencyScore += completionScore * 0.35;
    totalWeight += 0.35;

    // 2. Time Efficiency (20% weight) - Reduced from 25%
    const avgTimePerReport = getTeacherAvgTimePerReport(teacherId);
    let timeScore = 100;
    if (avgTimePerReport > 0) {
      // Benchmark: 5 minutes is excellent, 10 minutes is average, 15+ minutes needs improvement
      if (avgTimePerReport <= 5) {
        timeScore = 100;
      } else if (avgTimePerReport <= 10) {
        timeScore = 80;
      } else if (avgTimePerReport <= 15) {
        timeScore = 60;
      } else {
        timeScore = Math.max(40, 100 - (avgTimePerReport - 15) * 5); // Decrease by 5 points per minute over 15
      }
    }
    efficiencyScore += timeScore * 0.2;
    totalWeight += 0.2;

    // 3. Report Quality (20% weight) - Same weight
    let qualityScore = 0;
    let reportsWithQualityData = 0;
    
    teacherReports.forEach(report => {
      let reportQuality = 0;
      
      // Check if report has voice recording
      if (report.voiceRecording && report.voiceRecording.hasRecording) {
        reportQuality += 30;
      }
      
      // Check if report has transcription
      if (report.voiceRecording && report.voiceRecording.transcription) {
        reportQuality += 30;
      }
      
      // Check if report is AI generated
      if (report.aiGenerated) {
        if (typeof report.aiGenerated === 'boolean' && report.aiGenerated) {
          reportQuality += 20;
        } else if (typeof report.aiGenerated === 'object' && report.aiGenerated.isAiGenerated) {
          reportQuality += 20;
        }
      }
      
      // Check if report is completed/sent
      if (report.status === 'completed' || report.status === 'sent') {
        reportQuality += 20;
      }
      
      if (reportQuality > 0) {
        qualityScore += reportQuality;
        reportsWithQualityData++;
      }
    });
    
    const avgQualityScore = reportsWithQualityData > 0 ? qualityScore / reportsWithQualityData : 0;
    efficiencyScore += avgQualityScore * 0.2;
    totalWeight += 0.2;

    // 4. Frequency Compliance (15% weight) - NEW METRIC
    let frequencyScore = 0;
    if (teacherReports.length > 0) {
      // Group reports by student to analyze frequency compliance
      const reportsByStudent: { [studentId: string]: any[] } = {};
      
      teacherReports.forEach(report => {
        const studentId = typeof report.studentId === 'string' ? report.studentId : report.studentId._id;
        if (!reportsByStudent[studentId]) {
          reportsByStudent[studentId] = [];
        }
        reportsByStudent[studentId].push(report);
      });

      let totalFrequencyCompliance = 0;
      let studentsWithReports = 0;

      Object.values(reportsByStudent).forEach(studentReports => {
        if (studentReports.length >= 2) {
          // Sort reports by creation date
          const sortedReports = studentReports.sort((a, b) => 
            new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
          );

          // Calculate average time between reports
          let totalDaysBetweenReports = 0;
          let reportIntervals = 0;

          for (let i = 1; i < sortedReports.length; i++) {
            const daysBetween = (new Date(sortedReports[i].createdAt).getTime() - 
                               new Date(sortedReports[i-1].createdAt).getTime()) / (1000 * 60 * 60 * 24);
            totalDaysBetweenReports += daysBetween;
            reportIntervals++;
          }

          const avgDaysBetweenReports = reportIntervals > 0 ? totalDaysBetweenReports / reportIntervals : 0;
          
          // Score based on frequency (assuming monthly frequency as default)
          // Monthly = 30 days, Weekly = 7 days, etc.
          let expectedFrequency = 30; // Default to monthly
          
          // Try to get frequency from template if available
          if (sortedReports[0].template) {
            // This would need to be enhanced to get actual template frequency
            // For now, we'll use a reasonable default
            expectedFrequency = 30;
          }

          let studentFrequencyScore = 100;
          if (avgDaysBetweenReports > 0) {
            // If reports are generated more frequently than expected, that's good
            if (avgDaysBetweenReports <= expectedFrequency) {
              studentFrequencyScore = 100;
            } else if (avgDaysBetweenReports <= expectedFrequency * 1.5) {
              studentFrequencyScore = 80;
            } else if (avgDaysBetweenReports <= expectedFrequency * 2) {
              studentFrequencyScore = 60;
            } else {
              studentFrequencyScore = Math.max(40, 100 - (avgDaysBetweenReports - expectedFrequency * 2) / 10);
            }
          }

          totalFrequencyCompliance += studentFrequencyScore;
          studentsWithReports++;
        } else {
          // Single report - give partial credit
          totalFrequencyCompliance += 50;
          studentsWithReports++;
        }
      });

      frequencyScore = studentsWithReports > 0 ? totalFrequencyCompliance / studentsWithReports : 0;
    }
    efficiencyScore += frequencyScore * 0.15;
    totalWeight += 0.15;

    // 5. Consistency (10% weight) - Reduced from 15%
    let consistencyScore = 0;
    if (teacherReports.length > 0) {
      // Check if reports are spread over time (not all created on same day)
      const reportDates = teacherReports.map(report => new Date(report.createdAt).toDateString());
      const uniqueDates = new Set(reportDates).size;
      const totalReports = teacherReports.length;
      
      // Consistency score based on report distribution
      if (uniqueDates >= Math.min(totalReports, 3)) {
        consistencyScore = 100; // Good distribution
      } else if (uniqueDates >= Math.min(totalReports, 2)) {
        consistencyScore = 80; // Moderate distribution
      } else {
        consistencyScore = 60; // Poor distribution
      }
    }
    efficiencyScore += consistencyScore * 0.1;
    totalWeight += 0.1;

    // Calculate final efficiency score
    const finalEfficiency = totalWeight > 0 ? efficiencyScore / totalWeight : 0;
    
    console.log(`TeacherManagement - Teacher ${teacherId} efficiency breakdown:`, {
      completionRate: `${teacherReports.length}/${teacherStudents}`,
      completionScore: completionScore.toFixed(1),
      avgTimePerReport: avgTimePerReport.toFixed(1),
      timeScore: timeScore.toFixed(1),
      avgQualityScore: avgQualityScore.toFixed(1),
      frequencyScore: frequencyScore.toFixed(1),
      consistencyScore: consistencyScore.toFixed(1),
      finalEfficiency: finalEfficiency.toFixed(1)
    });
    
    return Math.round(finalEfficiency);
  };

  // Helper to title-case names for display
  const formatWordCase = (text: string) => {
    if (!text) return text;
    return text
      .split(' ')
      .filter(Boolean)
      .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
      .join(' ');
  };

  // Get available grades from school data and format them for display
  const availableGrades = school.gradeLevels || [];
  
  console.log('TeacherManagement - school object:', school);
  console.log('TeacherManagement - availableGrades:', availableGrades);
  const formatGradeForDisplay = (grade: string) => {
    if (!grade) return grade;
    const lower = grade.toLowerCase();
    switch (lower) {
      // Daycare / early childhood
      case 'infant': return 'Infant';
      case 'toddler': return 'Toddler';
      case 'preschool': return 'Preschool';
      case 'kindergarten': return 'Kindergarten';
      case 'primary_junior_school_age': return 'Primary/Junior School Age';
      case 'junior_school_age': return 'Junior School Age';

      // Montessori
      case 'infant_community_nido': return 'Infant Community (Nido)';
      case 'pre_casa_toddler': return 'Pre-Casa (Toddler)';
      case 'casa_childrens_house': return "Casa (Children's House)";
      case 'sr_casa': return 'Sr. Casa';
      case 'lower_elementary': return 'Lower Elementary';
      case 'upper_elementary': return 'Upper Elementary';
      case 'secondary': return 'Secondary';

      // Public/Private
      case 'junior_kindergarten_jk': return 'Junior Kindergarten (JK)';
      case 'senior_kindergarten_sk': return 'Senior Kindergarten (SK)';

      // Standard grades
      case 'grade1': return 'Grade 1';
      case 'grade2': return 'Grade 2';
      case 'grade3': return 'Grade 3';
      case 'grade4': return 'Grade 4';
      case 'grade5': return 'Grade 5';
      case 'grade6': return 'Grade 6';
      case 'grade7': return 'Grade 7';
      case 'grade8': return 'Grade 8';
      case 'grade9': return 'Grade 9';
      case 'grade10': return 'Grade 10';
      case 'grade11': return 'Grade 11';
      case 'grade12': return 'Grade 12';
      default: {
        // Generic prettifier for unforeseen raw codes
        const title = lower
          .replace(/_/g, ' ')
          .split(' ')
          .map(w => (w ? w.charAt(0).toUpperCase() + w.slice(1) : w))
          .join(' ');
        return title;
      }
    }
  };

  const formatGradeForDatabase = (grade: string) => {
    if (!grade) return grade as any;
    switch (grade) {
      // Daycare / early childhood (display -> raw)
      case 'Infant': return 'infant';
      case 'Toddler': return 'toddler';
      case 'Preschool': return 'preschool';
      case 'Kindergarten': return 'kindergarten';
      case 'Primary/Junior School Age': return 'primary_junior_school_age';
      case 'Junior School Age': return 'junior_school_age';

      // Montessori
      case 'Infant Community (Nido)': return 'infant_community_nido';
      case 'Pre-Casa (Toddler)': return 'pre_casa_toddler';
      case "Casa (Children's House)": return 'casa_childrens_house';
      case 'Sr. Casa': return 'sr_casa';
      case 'Lower Elementary': return 'lower_elementary';
      case 'Upper Elementary': return 'upper_elementary';
      case 'Secondary': return 'secondary';

      // Public/Private
      case 'Junior Kindergarten (JK)': return 'junior_kindergarten_jk';
      case 'Senior Kindergarten (SK)': return 'senior_kindergarten_sk';

      // Standard grades
      case 'Grade 1': return 'grade1';
      case 'Grade 2': return 'grade2';
      case 'Grade 3': return 'grade3';
      case 'Grade 4': return 'grade4';
      case 'Grade 5': return 'grade5';
      case 'Grade 6': return 'grade6';
      case 'Grade 7': return 'grade7';
      case 'Grade 8': return 'grade8';
      case 'Grade 9': return 'grade9';
      case 'Grade 10': return 'grade10';
      case 'Grade 11': return 'grade11';
      case 'Grade 12': return 'grade12';
      default: {
        return grade
          .toLowerCase()
          .replace(/[\s/]+/g, '_')
          .replace(/[()'']/g, '')
          .replace(/__+/g, '_');
      }
    }
  };

  // Function to normalize any grade format to display format
  const normalizeGradeForDisplay = (grade: string) => {
    return formatGradeForDisplay(grade);
  };

  const [snackbar, setSnackbar] = useState<{
    open: boolean;
    message: string;
    severity: 'success' | 'error' | 'info' | 'warning';
  }>({
    open: false,
    message: '',
    severity: 'success',
  });

  const showSnackbar = (message: string, severity: 'success' | 'error' | 'info' | 'warning' = 'success') => {
    setSnackbar({
      open: true,
      message,
      severity,
    });
  };

  const handleCloseSnackbar = () => {
    setSnackbar(prev => ({ ...prev, open: false }));
  };
  
  // Debug: Log teachers data
  console.log('TeacherManagement - teachers:', teachers);
  console.log('TeacherManagement - teachers length:', teachers.length);
  console.log('TeacherManagement - students:', students);
  console.log('TeacherManagement - students length:', students.length);
  console.log('TeacherManagement - classes:', classes);
  console.log('TeacherManagement - classes length:', classes.length);
  console.log('TeacherManagement - reports:', reports);
  console.log('TeacherManagement - reports length:', reports.length);
  
  // Debug: Log sample report voice recording data
  if (reports.length > 0) {
    console.log('TeacherManagement - Sample report voice recording data:', reports[0].voiceRecording);
    console.log('TeacherManagement - Sample report AI generated data:', reports[0].aiGenerated);
  }
  
  console.log('TeacherManagement - school:', school);

  // Filter teachers based on search and filters
  const filteredTeachers = teachers.filter(teacher => {
    const fullName = `${teacher.firstName || ''} ${teacher.lastName || ''}`.toLowerCase();
    const email = teacher.email.toLowerCase();
    const matchesSearch = searchTerm === '' || 
      fullName.includes(searchTerm.toLowerCase()) || 
      email.includes(searchTerm.toLowerCase());
    
    // Handle grade filtering - compare formatted grades
    const teacherGradeFormatted = formatGradeForDisplay(teacher.grade || '');
    const matchesGrade = filterGrade === '' || teacherGradeFormatted === filterGrade;
    
    const matchesStatus = filterStatus === '' || (teacher.isActive ? 'active' : 'inactive') === filterStatus;
    
    const matchesEmailPermission = filterEmailPermission === '' || 
      (filterEmailPermission === 'allowed' && teacher.canEmailReports) ||
      (filterEmailPermission === 'not-allowed' && !teacher.canEmailReports);
    
    return matchesSearch && matchesGrade && matchesStatus && matchesEmailPermission;
  });

  console.log('TeacherManagement - filteredTeachers length:', filteredTeachers.length);

  const teacherStats = {
    totalTeachers: teachers.length,
    activeTeachers: teachers.filter(t => t.isActive !== false).length,
    totalStudents: students ? students.length : 0,
    totalReports: teachers.reduce((sum, t) => sum + getTeacherReportCount(t._id || t.id || ''), 0),
    avgReportsPerTeacher: Math.round(teachers.reduce((sum, t) => sum + getTeacherReportCount(t._id || t.id || ''), 0) / teachers.length) || 0,
    avgTimePerReport: Math.round(teachers.reduce((sum, t) => sum + getTeacherAvgTimePerReport(t._id || t.id || ''), 0) / teachers.length * 10) / 10 || 0,
    avgEfficiency: Math.round(teachers.reduce((sum, t) => sum + getTeacherEfficiency(t._id || t.id || ''), 0) / teachers.length) || 0,
  };

  const trainingResources = [
    {
      id: 1,
      title: 'Voice Recording Best Practices',
      type: 'video',
      duration: '15 min',
      description: 'Learn how to record clear voice notes for optimal AI processing',
      completed: 24,
      total: 28,
    },
    {
      id: 2,
      title: 'Report Review and Editing',
      type: 'guide',
      duration: '20 min',
      description: 'How to effectively review and edit AI-generated reports',
      completed: 18,
      total: 28,
    },
    {
      id: 3,
      title: 'System Navigation Tutorial',
      type: 'interactive',
      duration: '10 min',
      description: 'Complete walkthrough of the teacher interface',
      completed: 28,
      total: 28,
    },
  ];

  const grades = availableGrades.length > 0 
    ? availableGrades.map(formatGradeForDisplay) 
    : [];
    
  console.log('TeacherManagement - grades array:', grades);

  const getEfficiencyColor = (efficiency: number) => {
    if (efficiency >= 90) return 'success';
    if (efficiency >= 80) return 'warning';
    return 'error';
  };

  const getEfficiencyIcon = (efficiency: number) => {
    if (efficiency >= 90) return <TrendingUp color="success" />;
    if (efficiency >= 80) return <TrendingDown color="warning" />;
    return <TrendingDown color="error" />;
  };

  const getSubjectIcon = (subject: string) => {
    const subjectIcons: { [key: string]: any } = {
      math: <Work />,
      science: <Science />,
      english: <Language />,
      history: <History />,
      art: <Work />,
      music: <MusicNote />,
      pe: <Sports />,
      computer: <Computer />,
      biology: <Science />,
      chemistry: <Science />,
      physics: <Science />,
      psychology: <Psychology />,
      geography: <Public />,
    };
    return subjectIcons[subject.toLowerCase()] || <Work />;
  };

  const getGradeColor = (grade: string) => {
    const gradeColors: { [key: string]: string } = {
      preschool: '#ff9800',
      kindergarten: '#4caf50',
      grade1: '#2196f3',
      grade2: '#9c27b0',
      grade3: '#f44336',
      grade4: '#00bcd4',
      grade5: '#8bc34a',
      grade6: '#ff5722',
      grade7: '#3f51b5',
      grade8: '#009688',
      grade9: '#e91e63',
      grade10: '#795548',
      grade11: '#607d8b',
      grade12: '#9e9e9e',
    };
    return gradeColors[grade.toLowerCase()] || '#666';
  };

  const handleSort = (field: string) => {
    if (sortBy === field) {
      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
    } else {
      setSortBy(field);
      setSortOrder('asc');
    }
  };

  const sortedTeachers = [...filteredTeachers].sort((a, b) => {
    let aValue, bValue;
    
    switch (sortBy) {
      case 'name':
        aValue = `${a.firstName || ''} ${a.lastName || ''}`.toLowerCase();
        bValue = `${b.firstName || ''} ${b.lastName || ''}`.toLowerCase();
        break;
      case 'grade':
        aValue = a.grade || '';
        bValue = b.grade || '';
        break;
      case 'students':
        aValue = getTeacherStudentCount(a._id || a.id || '');
        bValue = getTeacherStudentCount(b._id || b.id || '');
        break;
      case 'reports':
        aValue = getTeacherReportCount(a._id || a.id || '');
        bValue = getTeacherReportCount(b._id || b.id || '');
        break;
      case 'avgTimePerReport':
        aValue = getTeacherAvgTimePerReport(a._id || a.id || '');
        bValue = getTeacherAvgTimePerReport(b._id || b.id || '');
        break;
      case 'efficiency':
        aValue = getTeacherEfficiency(a._id || a.id || '');
        bValue = getTeacherEfficiency(b._id || b.id || '');
        break;
      default:
        aValue = (a as any)[sortBy] || '';
        bValue = (b as any)[sortBy] || '';
    }
    
    if (sortOrder === 'asc') {
      return aValue > bValue ? 1 : -1;
    } else {
      return aValue < bValue ? 1 : -1;
    }
  });

  const handleOpenTeacherDialog = (type: 'add' | 'edit' | 'view', teacherId?: string) => {
    setDialogType(type);
    setOpenTeacherDialog(true);
    
    if (type === 'add') {
      setTeacherForm({
        name: '',
        email: '',
        phone: '',
        grade: '',
        password: '',
        sendWelcomeEmail: true,
        canEmailReports: false,
        hireDate: '',
        specialization: '',
        qualifications: '',
        bio: '',
        isActive: true,
      });
      setSelectedTeacher(null);
    } else if (teacherId) {
      const teacher = teachers.find(t => (t.id === teacherId) || (t._id === teacherId));
      if (teacher) {
        setSelectedTeacher(teacher);
        const fullName = `${teacher.firstName || ''} ${teacher.lastName || ''}`.trim();
        setTeacherForm({
          name: fullName,
          email: teacher.email,
          phone: teacher.phone || '',
          grade: teacher.grade || '',
          password: '',
          sendWelcomeEmail: false,
          canEmailReports: !!teacher.canEmailReports,
          hireDate: teacher.hireDate ? new Date(teacher.hireDate).toISOString().split('T')[0] : '',
          specialization: teacher.specialization || '',
          qualifications: teacher.qualifications || '',
          bio: teacher.bio || '',
          isActive: teacher.isActive !== false, // Default to true if not explicitly false
        });
      }
    }
  };

  const handleCloseTeacherDialog = () => {
    setOpenTeacherDialog(false);
    setTeacherForm({
      name: '',
      email: '',
      phone: '',
      grade: '',
      password: '',
      sendWelcomeEmail: true,
      canEmailReports: false,
      hireDate: '',
      specialization: '',
      qualifications: '',
      bio: '',
      isActive: true,
    });
    setSelectedTeacher(null);
  };

  const handleFormChange = (field: string, value: string | boolean) => {
    setTeacherForm(prev => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleSaveTeacher = async () => {
    try {
      // Validate required fields
      if (!teacherForm.name.trim()) {
        showSnackbar('Teacher name is required', 'error');
        return;
      }
      
      if (dialogType === 'add') {
        // Generate avatar initials from name
        const nameParts = teacherForm.name.trim().split(' ');
        const firstName = nameParts[0] || '';
        const lastName = nameParts.length > 1 ? nameParts.slice(1).join(' ') : firstName; // Use firstName as lastName if only one name
        
        const avatar = nameParts.length >= 2 
          ? `${firstName[0]}${lastName[0]}`.toUpperCase()
          : teacherForm.name.substring(0, 2).toUpperCase();

        console.log('TeacherManagement - Adding teacher:', {
          firstName: firstName,
          lastName: lastName,
          email: teacherForm.email,
          phone: teacherForm.phone,
          grade: teacherForm.grade,
          schoolId: school.id,
        });

        // Prepare teacher data
        const generatedPassword = (teacherForm.password && teacherForm.password.length >= 8) 
          ? teacherForm.password 
          : 'TeacherPass123';
        console.log('TeacherManagement - teacherForm.password:', teacherForm.password);
        console.log('TeacherManagement - Generated password:', generatedPassword);
        console.log('TeacherManagement - Password length:', generatedPassword.length);
        
        const teacherData: any = {
          firstName: firstName,
          lastName: lastName,
          email: teacherForm.email,
          phone: teacherForm.phone,
          grade: teacherForm.grade,
          password: generatedPassword,
          canEmailReports: teacherForm.canEmailReports,
          students: 0,
          reportsGenerated: 0,
          lastLogin: 'Never',
          status: 'active' as const,
          avgTimePerReport: 0,
          efficiency: 0,
          avatar,
          hireDate: teacherForm.hireDate,
          specialization: teacherForm.specialization,
          qualifications: teacherForm.qualifications,
          bio: teacherForm.bio,
          performanceScore: 0,
          trainingCompleted: [],
          subjects: [],
        };

        // Set schoolId based on user role
        if (user?.role === 'school_admin') {
          // School admins can only create teachers for their own school
          // Extract _id from schoolId object if it's an object
          teacherData.schoolId = typeof user.schoolId === 'object' && user.schoolId?._id 
            ? user.schoolId._id 
            : user.schoolId;
        } else if (user?.role === 'super_admin' && school?.id) {
          // Super admins can create teachers for any school
          teacherData.schoolId = school.id;
        }

        console.log('TeacherManagement - Final teacherData being sent:', teacherData);
        console.log('TeacherManagement - School ID:', school.id);
        console.log('TeacherManagement - User role:', user?.role);
        console.log('TeacherManagement - User schoolId:', user?.schoolId);
        console.log('TeacherManagement - User object:', user);

        const result = await addTeacher(teacherData);
        console.log('TeacherManagement - addTeacher result:', result);
        
        // Force refresh the data to ensure we have the latest teachers
        await refreshData();
        
        showSnackbar('Teacher added successfully!', 'success');
      } else if (dialogType === 'edit' && selectedTeacher) {
        console.log('TeacherManagement - Updating teacher:', {
          firstName: teacherForm.name.split(' ')[0] || '',
          lastName: teacherForm.name.split(' ').slice(1).join(' ') || '',
          email: teacherForm.email,
          phone: teacherForm.phone,
          grade: teacherForm.grade,
          hireDate: teacherForm.hireDate,
          specialization: teacherForm.specialization,
          qualifications: teacherForm.qualifications,
          bio: teacherForm.bio,
          isActive: teacherForm.isActive,
        });

        await updateTeacher(selectedTeacher.id || selectedTeacher._id, {
          firstName: teacherForm.name.split(' ')[0] || '',
          lastName: teacherForm.name.split(' ').slice(1).join(' ') || '',
          email: teacherForm.email,
          phone: teacherForm.phone,
          grade: teacherForm.grade,
          hireDate: teacherForm.hireDate,
          specialization: teacherForm.specialization,
          qualifications: teacherForm.qualifications,
          bio: teacherForm.bio,
          isActive: teacherForm.isActive,
          canEmailReports: teacherForm.canEmailReports,
        });
        
        // Force refresh the data to ensure we have the latest teachers
        await refreshData();
        
        showSnackbar('Teacher updated successfully!', 'success');
      }
      
      handleCloseTeacherDialog();
    } catch (error) {
      console.error('Error saving teacher:', error);
      
      // Show more detailed error information
      let errorMessage = 'Error saving teacher. Please try again.';
      
      if (error instanceof Error) {
        errorMessage = error.message;
      } else if (typeof error === 'object' && error !== null) {
        errorMessage = JSON.stringify(error);
      }
      
      console.error('Detailed error:', errorMessage);
      showSnackbar(errorMessage, 'error');
    }
  };

  const handleDeleteTeacher = (teacher: any) => {
    setTeacherToDelete(teacher);
    setOpenDeleteDialog(true);
  };

  const confirmDeleteTeacher = () => {
    if (teacherToDelete) {
      deleteTeacher(teacherToDelete.id);
      showSnackbar('Teacher deleted successfully!', 'success');
      setTeacherToDelete(null);
      setOpenDeleteDialog(false);
    }
  };

  const handleClearFilters = () => {
    setSearchTerm('');
    setFilterGrade('');
    setFilterStatus('');
    setFilterEmailPermission('');
    showSnackbar('Filters cleared!', 'info');
  };

  // Helper function to get random card color
  const getRandomCardColor = (index: number) => {
    return themeColors.cardColors[index % themeColors.cardColors.length];
  };

  return (
    <Container maxWidth="xl">
      {/* School Banner */}
      {schoolBranding && (
        <Fade in timeout={600}>
          <Paper
            elevation={0}
            sx={{
              background: `linear-gradient(135deg, ${schoolBranding.branding?.primaryColor || schoolBranding.primaryColor || '#273890'} 0%, ${schoolBranding.branding?.secondaryColor || schoolBranding.secondaryColor || '#7f0f4a'} 100%)`,
              borderRadius: 4,
              p: 3,
              mb: 4,
              mt: 0,
              color: 'white',
              position: 'relative',
              overflow: 'hidden',
            }}
          >
            <Grid container spacing={2} alignItems="center">
              <Grid item xs={12} md={9}>
                <Typography variant="h4" sx={{ fontWeight: 700, mb: 1 }}>
                  {schoolBranding.name || 'School Name'}
                </Typography>
                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 2, alignItems: 'center' }}>
                  {schoolBranding.established && (
                    <Typography variant="body2" sx={{ opacity: 0.95 }}>
                      📅 Est. {schoolBranding.established}
                    </Typography>
                  )}
                {schoolBranding.address && (
                  <Typography variant="body2" sx={{ opacity: 0.95 }}>
                    📍 {typeof schoolBranding.address === 'string' 
                      ? schoolBranding.address 
                      : `${schoolBranding.address.street}, ${schoolBranding.address.city}, ${schoolBranding.address.state}`}
                  </Typography>
                )}
                  {schoolBranding.email && (
                    <Typography variant="body2" sx={{ opacity: 0.95 }}>
                      ✉️ {schoolBranding.email}
                    </Typography>
                  )}
                  {schoolBranding.phone && (
                    <Typography variant="body2" sx={{ opacity: 0.95 }}>
                      📞 {schoolBranding.phone}
                    </Typography>
                  )}
                </Box>
              </Grid>
              <Grid item xs={12} md={3}>
                {(schoolBranding.logo || schoolBranding.branding?.logo) && (() => {
                  const logoPath = schoolBranding.logo || schoolBranding.branding?.logo || '';
                  const logoUrl = logoPath.startsWith('http://') || logoPath.startsWith('https://') 
                    ? logoPath 
                    : `${(process.env.REACT_APP_API_URL || 'http://localhost:5050').replace('/api', '')}${logoPath.startsWith('/') ? logoPath : '/' + logoPath}`;
                  return (
                    <Box sx={{ display: 'flex', justifyContent: 'flex-end' }}>
                      <Box sx={{
                        bgcolor: 'rgba(255,255,255,0.95)',
                        borderRadius: 3,
                        p: 2,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                      }}>
                        <img 
                          src={logoUrl} 
                          alt={schoolBranding.name}
                          style={{ 
                            maxWidth: '120px',
                            maxHeight: '120px',
                            objectFit: 'contain'
                          }}
                        />
                      </Box>
                    </Box>
                  );
                })()}
              </Grid>
            </Grid>
          </Paper>
        </Fade>
      )}

      {/* Header with Notification Icon */}
      <Box sx={{ mb: 4, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <Fade in timeout={800}>
          <Typography 
            variant="h4" 
            sx={{ 
              fontWeight: 700,
              background: schoolBranding 
                ? `linear-gradient(135deg, ${schoolBranding.branding?.primaryColor || schoolBranding.primaryColor || '#667eea'} 0%, ${schoolBranding.branding?.secondaryColor || schoolBranding.secondaryColor || '#764ba2'} 100%)`
                : 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
              backgroundClip: 'text',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              textShadow: '0 2px 4px rgba(0,0,0,0.1)',
            }}
          >
            Teacher & Staff Management
          </Typography>
        </Fade>
        <NotificationIcon />
      </Box>

      {/* Summary Statistics */}
      <Grow in timeout={900}>
        <Box sx={{ mb: 3 }}>
          <Grid container spacing={3}>
            <Grid item xs={12} sm={6} md={2}>
              <Paper
                elevation={0}
                sx={{
                  background: getRandomCardColor(0),
                  borderRadius: 3,
                  backdropFilter: 'blur(10px)',
                  border: '1px solid rgba(255,255,255,0.3)',
                  p: 2,
                  textAlign: 'center',
                  transition: 'all 0.3s ease',
                  '&:hover': {
                    transform: 'translateY(-2px)',
                    boxShadow: '0 8px 25px rgba(0,0,0,0.1)',
                  },
                }}
              >
                <Typography variant="h4" sx={{ fontWeight: 700, color: '#667eea', mb: 1 }}>
                  {teacherStats.totalTeachers}
                </Typography>
                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                  Total Teachers
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} sm={6} md={2}>
              <Paper
                elevation={0}
                sx={{
                  background: getRandomCardColor(0),
                  borderRadius: 3,
                  backdropFilter: 'blur(10px)',
                  border: '1px solid rgba(255,255,255,0.3)',
                  p: 2,
                  textAlign: 'center',
                  transition: 'all 0.3s ease',
                  '&:hover': {
                    transform: 'translateY(-2px)',
                    boxShadow: '0 8px 25px rgba(0,0,0,0.1)',
                  },
                }}
              >
                <Typography variant="h4" sx={{ fontWeight: 700, color: '#4caf50', mb: 1 }}>
                  {teacherStats.totalStudents}
                </Typography>
                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                  Total Students
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} sm={6} md={2}>
              <Paper
                elevation={0}
                sx={{
                  background: getRandomCardColor(0),
                  borderRadius: 3,
                  backdropFilter: 'blur(10px)',
                  border: '1px solid rgba(255,255,255,0.3)',
                  p: 2,
                  textAlign: 'center',
                  transition: 'all 0.3s ease',
                  '&:hover': {
                    transform: 'translateY(-2px)',
                    boxShadow: '0 8px 25px rgba(0,0,0,0.1)',
                  },
                }}
              >
                <Typography variant="h4" sx={{ fontWeight: 700, color: '#ff9800', mb: 1 }}>
                  {teacherStats.totalReports}
                </Typography>
                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                  Total Reports
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} sm={6} md={2}>
              <Paper
                elevation={0}
                sx={{
                  background: getRandomCardColor(0),
                  borderRadius: 3,
                  backdropFilter: 'blur(10px)',
                  border: '1px solid rgba(255,255,255,0.3)',
                  p: 2,
                  textAlign: 'center',
                  transition: 'all 0.3s ease',
                  '&:hover': {
                    transform: 'translateY(-2px)',
                    boxShadow: '0 8px 25px rgba(0,0,0,0.1)',
                  },
                }}
              >
                <Typography variant="h4" sx={{ fontWeight: 700, color: '#9c27b0', mb: 1 }}>
                  {teacherStats.activeTeachers}
                </Typography>
                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                  Active Teachers
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} sm={6} md={2}>
              <Paper
                elevation={0}
                sx={{
                  background: getRandomCardColor(0),
                  borderRadius: 3,
                  backdropFilter: 'blur(10px)',
                  border: '1px solid rgba(255,255,255,0.3)',
                  p: 2,
                  textAlign: 'center',
                  transition: 'all 0.3s ease',
                  '&:hover': {
                    transform: 'translateY(-2px)',
                    boxShadow: '0 8px 25px rgba(0,0,0,0.1)',
                  },
                }}
              >
                <Typography variant="h4" sx={{ fontWeight: 700, color: '#e91e63', mb: 1 }}>
                  {teacherStats.avgTimePerReport}
                </Typography>
                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                  Avg Time/Report (min)
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} sm={6} md={2}>
              <Paper
                elevation={0}
                sx={{
                  background: getRandomCardColor(0),
                  borderRadius: 3,
                  backdropFilter: 'blur(10px)',
                  border: '1px solid rgba(255,255,255,0.3)',
                  p: 2,
                  textAlign: 'center',
                  transition: 'all 0.3s ease',
                  '&:hover': {
                    transform: 'translateY(-2px)',
                    boxShadow: '0 8px 25px rgba(0,0,0,0.1)',
                  },
                }}
              >
                <Typography variant="h4" sx={{ fontWeight: 700, color: '#00bcd4', mb: 1 }}>
                  {teacherStats.avgEfficiency}%
                </Typography>
                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                  Avg Efficiency
                </Typography>
              </Paper>
            </Grid>
          </Grid>
        </Box>
      </Grow>

      {/* Search and Actions */}
      <Grow in timeout={1000}>
        <Paper
          elevation={0}
          sx={{
            background: 'rgba(255,255,255,0.8)',
            borderRadius: 4,
            backdropFilter: 'blur(10px)',
            border: '1px solid rgba(255,255,255,0.3)',
            boxShadow: '0 8px 32px rgba(0,0,0,0.1)',
            mb: 3,
            transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
            '&:hover': {
              transform: 'translateY(-2px)',
              boxShadow: '0 12px 40px rgba(0,0,0,0.15)',
            },
          }}
        >
          <CardContent sx={{ p: 3 }}>
            <Grid container spacing={2} alignItems="center">
              <Grid item xs={12} sm={6} md={3}>
                <TextField
                  fullWidth
                  placeholder="Search teachers..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  InputProps={{
                    startAdornment: <Search sx={{ mr: 1, color: 'text.secondary' }} />,
                  }}
                  sx={{
                    '& .MuiOutlinedInput-root': {
                      borderRadius: 3,
                      '&:hover .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}80`,
                      },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
                        borderColor: primaryColor,
                      },
                    },
                  }}
                />
              </Grid>
              <Grid item xs={12} sm={6} md={2}>
                <FormControl fullWidth>
                  <InputLabel>Grade</InputLabel>
                  <Select
                    value={filterGrade}
                    onChange={(e) => setFilterGrade(e.target.value)}
                    label="Grade"
                    sx={{
                      borderRadius: 3,
                      '& .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}4D`,
                      },
                      '&:hover .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}80`,
                      },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
                        borderColor: primaryColor,
                      },
                    }}
                  >
                    <MenuItem value="">All Grades</MenuItem>
                    {grades.map((grade) => (
                      <MenuItem key={grade} value={grade}>{grade}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12} sm={6} md={2}>
                <FormControl fullWidth>
                  <InputLabel>Status</InputLabel>
                  <Select
                    value={filterStatus}
                    onChange={(e) => setFilterStatus(e.target.value)}
                    label="Status"
                    sx={{
                      borderRadius: 3,
                      '& .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}4D`,
                      },
                      '&:hover .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}80`,
                      },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
                        borderColor: primaryColor,
                      },
                    }}
                  >
                    <MenuItem value="">All Status</MenuItem>
                    <MenuItem value="active">Active</MenuItem>
                    <MenuItem value="inactive">Inactive</MenuItem>
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12} sm={6} md={2}>
                <FormControl fullWidth>
                  <InputLabel>Email Permission</InputLabel>
                  <Select
                    value={filterEmailPermission}
                    onChange={(e) => setFilterEmailPermission(e.target.value)}
                    label="Email Permission"
                    sx={{
                      borderRadius: 3,
                      '& .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}4D`,
                      },
                      '&:hover .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}80`,
                      },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
                        borderColor: primaryColor,
                      },
                    }}
                  >
                    <MenuItem value="">All Permissions</MenuItem>
                    <MenuItem value="allowed">Email Allowed</MenuItem>
                    <MenuItem value="not-allowed">Email Not Allowed</MenuItem>
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12} sm={12} md={3}>
                <Box sx={{ display: 'flex', gap: 1.5, justifyContent: 'flex-end' }}>
                  <Button
                    variant="outlined"
                    color="primary"
                    startIcon={<Refresh />}
                    onClick={handleClearFilters}
                    disabled={!searchTerm && !filterGrade && !filterStatus && !filterEmailPermission}
                    sx={{
                      borderRadius: 3,
                      px: 2,
                      py: 1.5,
                      fontWeight: 600,
                      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                    }}
                  >
                    Clear
                  </Button>
                  <Button
                    variant="contained"
                    startIcon={<Add />}
                    onClick={() => handleOpenTeacherDialog('add')}
                    sx={{
                      background: brandingGradient,
                      borderRadius: 3,
                      px: 3,
                      py: 1.5,
                      fontWeight: 600,
                      boxShadow: `0 4px 12px ${primaryColor}4D`,
                      '&:hover': {
                        background: brandingGradientHover,
                        transform: 'translateY(-2px)',
                        boxShadow: `0 6px 20px ${primaryColor}66`,
                      },
                      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                    }}
                  >
                    Add Teacher
                  </Button>
                </Box>
              </Grid>
            </Grid>
          </CardContent>
        </Paper>
      </Grow>

      {/* Filter Summary */}
              {(searchTerm || filterGrade || filterStatus || filterEmailPermission) && (
        <Grow in timeout={600}>
          <Box sx={{ mb: 2 }}>
            <Paper
              elevation={0}
              sx={{
                background: 'rgba(102, 126, 234, 0.05)',
                borderRadius: 3,
                border: '1px solid rgba(102, 126, 234, 0.2)',
                p: 2,
              }}
            >
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, flexWrap: 'wrap' }}>
                <Typography variant="body2" sx={{ fontWeight: 600, color: '#667eea' }}>
                  Active Filters:
                </Typography>
                {searchTerm && (
                  <Chip
                    label={`Search: "${searchTerm}"`}
                    size="small"
                    color="primary"
                    onDelete={() => setSearchTerm('')}
                    sx={{ borderRadius: 2 }}
                  />
                )}
                {filterGrade && (
                  <Chip
                    label={`Grade: ${filterGrade}`}
                    size="small"
                    color="primary"
                    onDelete={() => setFilterGrade('')}
                    sx={{ borderRadius: 2 }}
                  />
                )}
                {filterStatus && (
                  <Chip
                    label={`Status: ${filterStatus}`}
                    size="small"
                    color="primary"
                    onDelete={() => setFilterStatus('')}
                    sx={{ borderRadius: 2 }}
                  />
                )}
                {filterEmailPermission && (
                  <Chip
                    label={`Email: ${filterEmailPermission === 'allowed' ? 'Allowed' : 'Not Allowed'}`}
                    size="small"
                    color="primary"
                    onDelete={() => setFilterEmailPermission('')}
                    sx={{ borderRadius: 2 }}
                  />
                )}
                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                  Showing {filteredTeachers.length} of {teachers.length} teachers
                </Typography>
                <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                  Total Reports: {filteredTeachers.reduce((sum, t) => sum + getTeacherReportCount(t._id || t.id || ''), 0)}
                </Typography>
              </Box>
            </Paper>
          </Box>
        </Grow>
      )}

      {/* Teacher Directory Table */}
      <Grow in timeout={1400}>
        <Box>
          <TableContainer sx={{ overflowX: 'auto', borderRadius: 3, overflow: 'hidden', border: '1px solid rgba(0,0,0,0.06)' }}>
            <Table sx={{ minWidth: 800 }}>
              <TableHead>
                <TableRow sx={{ background: `${primaryColor}0D` }}>
                  <TableCell sx={{ fontWeight: 600, color: primaryColor }}>Teacher</TableCell>
                  <TableCell sx={{ fontWeight: 600, color: primaryColor }}>Grade</TableCell>
                  <TableCell sx={{ fontWeight: 600, color: primaryColor }}>Students</TableCell>
                  <TableCell sx={{ fontWeight: 600, color: primaryColor }}>Last Login</TableCell>
                  <TableCell sx={{ fontWeight: 600, color: primaryColor }}>Status</TableCell>
                  <TableCell sx={{ fontWeight: 600, color: primaryColor }}>
                    <Tooltip title="Permission to send reports directly to parents">
                      <Box sx={{ display: 'flex', alignItems: 'center', cursor: 'help' }}>
                        Email Reports
                        <Info sx={{ ml: 0.5, fontSize: '0.875rem', opacity: 0.7 }} />
                      </Box>
                    </Tooltip>
                  </TableCell>
                  <TableCell sx={{ fontWeight: 600, color: primaryColor }}>Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {sortedTeachers.map((teacher) => (
                  <TableRow 
                    key={teacher.id || teacher._id} 
                    hover
                    sx={{
                      '&:hover': {
                        background: `${primaryColor}0D`,
                      },
                      transition: 'all 0.2s ease-in-out',
                    }}
                  >
                    <TableCell>
                      <Box sx={{ display: 'flex', alignItems: 'center' }}>
                        <Avatar 
                          sx={{ 
                            mr: 2, 
                            background: brandingGradient,
                            boxShadow: `0 4px 12px ${primaryColor}40`,
                          }}
                        >
                          {teacher.avatar || `${(teacher.firstName || '').charAt(0).toUpperCase()}${(teacher.lastName || '').charAt(0).toUpperCase()}`}
                        </Avatar>
                        <Box>
                       <Typography 
                            variant="subtitle2"
                            sx={{ fontWeight: 600 }}
                          >
                            {`${formatWordCase(teacher.firstName || '')} ${formatWordCase(teacher.lastName || '')}`.trim()}
                          </Typography>
                          <Typography 
                            variant="caption" 
                            sx={{ 
                              color: 'text.secondary',
                              opacity: 0.8,
                            }}
                          >
                            {teacher.email}
                          </Typography>
                        </Box>
                      </Box>
                    </TableCell>
                    <TableCell>
                      <Typography sx={{ fontWeight: 500 }}>
                        {teacher.grade ? formatGradeForDisplay(teacher.grade) : 'N/A'}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Tooltip title={`Students across all assigned classes`}>
                        <Typography sx={{ fontWeight: 500 }}>
                          {getTeacherStudentCount(teacher._id || teacher.id || '')}
                        </Typography>
                      </Tooltip>
                    </TableCell>
                    <TableCell>
                      <Typography sx={{ fontWeight: 500 }}>
                        {teacher.lastLogin || 'Never'}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Chip
                        label={teacher.isActive ? 'Active' : 'Inactive'}
                        color={teacher.isActive ? 'success' : 'default'}
                        size="small"
                        sx={{
                          fontWeight: 600,
                          borderRadius: 2,
                        }}
                      />
                    </TableCell>
                    <TableCell>
                      <Tooltip title={teacher.canEmailReports ? "Can send reports to parents" : "Cannot send reports to parents"}>
                        <Chip
                          label={teacher.canEmailReports ? 'Allowed' : 'Not Allowed'}
                          color={teacher.canEmailReports ? 'success' : 'default'}
                          size="small"
                          icon={teacher.canEmailReports ? <CheckCircle sx={{ fontSize: 16 }} /> : <Warning sx={{ fontSize: 16 }} />}
                          sx={{
                            fontWeight: 600,
                            borderRadius: 2,
                            backgroundColor: teacher.canEmailReports ? '#e8f5e8' : '#f5f5f5',
                            color: teacher.canEmailReports ? '#2e7d32' : '#666',
                            '& .MuiChip-icon': {
                              color: teacher.canEmailReports ? '#4caf50' : '#ff9800',
                            }
                          }}
                        />
                      </Tooltip>
                    </TableCell>
                    <TableCell>
                      <Box sx={{ display: 'flex', gap: 1 }}>
                        <Tooltip title="View Details">
                          <IconButton
                            size="small"
                            onClick={() => handleOpenTeacherDialog('view', teacher.id || teacher._id)}
                            sx={{
                              color: primaryColor,
                              '&:hover': {
                                background: `${primaryColor}1A`,
                                transform: 'scale(1.1)',
                              },
                              transition: 'all 0.2s ease-in-out',
                            }}
                          >
                            <Visibility />
                          </IconButton>
                        </Tooltip>
                        <Tooltip title="Edit Teacher">
                          <IconButton
                            size="small"
                            onClick={() => handleOpenTeacherDialog('edit', teacher.id || teacher._id)}
                            sx={{
                              color: '#4caf50',
                              '&:hover': {
                                background: 'rgba(76, 175, 80, 0.1)',
                                transform: 'scale(1.1)',
                              },
                              transition: 'all 0.2s ease-in-out',
                            }}
                          >
                            <Edit />
                          </IconButton>
                        </Tooltip>
                        <Tooltip title="Delete Teacher">
                          <IconButton
                            size="small"
                            color="error"
                            onClick={() => handleDeleteTeacher(teacher)}
                            sx={{
                              color: '#f44336',
                              '&:hover': {
                                background: 'rgba(244, 67, 54, 0.1)',
                                transform: 'scale(1.1)',
                              },
                              transition: 'all 0.2s ease-in-out',
                            }}
                          >
                            <Delete />
                          </IconButton>
                        </Tooltip>
                        <Tooltip title={teacher.canEmailReports ? "Disable email reports" : "Enable email reports"}>
                          <IconButton
                            size="small"
                            onClick={async () => {
                              try {
                                await updateTeacher(teacher.id || teacher._id, {
                                  canEmailReports: !teacher.canEmailReports
                                });
                                await refreshData();
                                showSnackbar(
                                  `Email reports ${teacher.canEmailReports ? 'disabled' : 'enabled'} for ${teacher.firstName} ${teacher.lastName}`,
                                  'success'
                                );
                              } catch (error) {
                                console.error('Error updating email permission:', error);
                                showSnackbar('Error updating email permission', 'error');
                              }
                            }}
                            sx={{
                              color: teacher.canEmailReports ? '#f44336' : '#4caf50',
                              '&:hover': {
                                background: teacher.canEmailReports 
                                  ? 'rgba(244, 67, 54, 0.1)' 
                                  : 'rgba(76, 175, 80, 0.1)',
                                transform: 'scale(1.1)',
                              },
                              transition: 'all 0.2s ease-in-out',
                            }}
                          >
                            {teacher.canEmailReports ? <Email /> : <Email sx={{ opacity: 0.5 }} />}
                          </IconButton>
                        </Tooltip>
                      </Box>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
          
          {sortedTeachers.length === 0 && (
            <Box sx={{ textAlign: 'center', py: 4 }}>
              <Typography 
                variant="body1" 
                sx={{ 
                  color: 'text.secondary',
                  opacity: 0.8,
                  fontWeight: 500,
                  mb: 1,
                }}
              >
                {searchTerm || filterGrade || filterStatus || filterEmailPermission 
                  ? 'No teachers found matching your filters'
                  : 'No teachers found'
                }
              </Typography>
              {(searchTerm || filterGrade || filterStatus || filterEmailPermission) && (
                  <Button
                    variant="outlined"
                    color="primary"
                    size="small"
                    onClick={handleClearFilters}
                    sx={{ mt: 1 }}
                  >
                  Clear all filters
                </Button>
              )}
            </Box>
          )}
        </Box>
      </Grow>

      {/* Add/Edit Teacher Dialog */}
      <Dialog open={openTeacherDialog} onClose={handleCloseTeacherDialog} maxWidth="md" fullWidth>
        <DialogTitle
          sx={{
            background: brandingGradient,
            color: 'white',
            fontWeight: 700,
            fontSize: '1.5rem',
            textAlign: 'center',
            py: 3,
            position: 'relative',
            '&::after': {
              content: '""',
              position: 'absolute',
              bottom: 0,
              left: 0,
              right: 0,
              height: '2px',
              background: 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.5) 50%, transparent 100%)',
            }
          }}
        >
          {dialogType === 'add' && 'Add New Teacher'}
          {dialogType === 'edit' && 'Edit Teacher'}
          {dialogType === 'view' && 'Teacher Details'}
        </DialogTitle>
        <DialogContent sx={{ p: 3, pt: '24px !important' }}>
          {dialogType === 'view' ? (
            <Box>
              {selectedTeacher && (
                <Grid container spacing={3} sx={{ mt: 1 }}>
                  <Grid item xs={12} md={6}>
                    <Typography variant="h6" gutterBottom>Teacher Information</Typography>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Name</Typography>
                      <Typography variant="body1">{selectedTeacher.name}</Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Email</Typography>
                      <Typography variant="body1">{selectedTeacher.email}</Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Phone</Typography>
                      <Typography variant="body1">{selectedTeacher.phone}</Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Grade</Typography>
                      <Typography variant="body1">{selectedTeacher.grade}</Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Status</Typography>
                      <Chip
                        label={selectedTeacher.status}
                        color={selectedTeacher.status === 'active' ? 'success' : 'default'}
                        size="small"
                      />
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Hire Date</Typography>
                      <Typography variant="body1">{selectedTeacher.hireDate}</Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Specialization</Typography>
                      <Typography variant="body1">{selectedTeacher.specialization}</Typography>
                    </Box>
                  </Grid>
                  <Grid item xs={12} md={6}>
                    <Typography variant="h6" gutterBottom>Performance Metrics</Typography>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Students</Typography>
                      <Typography variant="body1">
                        {getTeacherStudentCount(selectedTeacher._id || selectedTeacher.id || '')}
                      </Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Reports Generated</Typography>
                      <Typography variant="body1">
                        {getTeacherReportCount(selectedTeacher._id || selectedTeacher.id || '')}
                      </Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Average Time per Report</Typography>
                      <Typography variant="body1">
                        {getTeacherAvgTimePerReport(selectedTeacher._id || selectedTeacher.id || '')} minutes
                      </Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Efficiency</Typography>
                      <Chip
                        label={`${getTeacherEfficiency(selectedTeacher._id || selectedTeacher.id || '')}%`}
                        color={getEfficiencyColor(getTeacherEfficiency(selectedTeacher._id || selectedTeacher.id || '')) as any}
                        size="small"
                      />
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Performance Score</Typography>
                      <Typography variant="body1">{selectedTeacher.performanceScore}%</Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Last Login</Typography>
                      <Typography variant="body1">{selectedTeacher.lastLogin}</Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Qualifications</Typography>
                      <Typography variant="body1">{selectedTeacher.qualifications}</Typography>
                    </Box>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary">Bio</Typography>
                      <Typography variant="body1">{selectedTeacher.bio}</Typography>
                    </Box>
                  </Grid>
                </Grid>
              )}
            </Box>
          ) : (
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid item xs={12} md={6}>
                <TextField 
                  fullWidth 
                  label="Full Name" 
                  value={teacherForm.name}
                  onChange={(e) => handleFormChange('name', e.target.value)}
                  required
                  sx={{
                    '& .MuiOutlinedInput-root': {
                      '&:hover .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}80`,
                      },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
                        borderColor: primaryColor,
                      },
                    },
                  }}
                />
              </Grid>
              <Grid item xs={12} md={6}>
                <TextField 
                  fullWidth 
                  label="Email" 
                  type="email" 
                  value={teacherForm.email}
                  onChange={(e) => handleFormChange('email', e.target.value)}
                  required
                  sx={{
                    '& .MuiOutlinedInput-root': {
                      '&:hover .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}80`,
                      },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
                        borderColor: primaryColor,
                      },
                    },
                  }}
                />
              </Grid>
              <Grid item xs={12} md={6}>
                <PhoneNumberInput
                  value={teacherForm.phone}
                  onChange={(value) => handleFormChange('phone', value)}
                  required
                  helperText="E.164 format (e.g., +1234567890) required for WhatsApp notifications"
                />
              </Grid>
              <Grid item xs={12} md={6}>
                <FormControl fullWidth required>
                  <InputLabel>Grade Level</InputLabel>
                  <Select 
                    label="Grade Level"
                    value={teacherForm.grade}
                    onChange={(e) => handleFormChange('grade', e.target.value)}
                    sx={{
                      '& .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}4D`,
                      },
                      '&:hover .MuiOutlinedInput-notchedOutline': {
                        borderColor: `${primaryColor}80`,
                      },
                      '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
                        borderColor: primaryColor,
                      },
                    }}
                  >
                    {grades.map(grade => (
                      <MenuItem key={grade} value={grade}>{grade}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12} md={6}>
                <TextField 
                  fullWidth 
                  label="Hire Date" 
                  type="date"
                  value={teacherForm.hireDate}
                  onChange={(e) => handleFormChange('hireDate', e.target.value)}
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>
              <Grid item xs={12} md={6}>
                <TextField 
                  fullWidth 
                  label="Specialization" 
                  value={teacherForm.specialization}
                  onChange={(e) => handleFormChange('specialization', e.target.value)}
                />
              </Grid>
              <Grid item xs={12} md={6}>
                <TextField 
                  fullWidth 
                  label="Qualifications" 
                  value={teacherForm.qualifications}
                  onChange={(e) => handleFormChange('qualifications', e.target.value)}
                />
              </Grid>
              <Grid item xs={12} md={6}>
                <TextField 
                  fullWidth 
                  label="Bio" 
                  value={teacherForm.bio}
                  onChange={(e) => handleFormChange('bio', e.target.value)}
                />
              </Grid>
              {dialogType === 'edit' && (
                <Grid item xs={12} md={6}>
                  <FormControlLabel
                    control={
                      <Switch 
                        checked={teacherForm.isActive}
                        onChange={(e) => handleFormChange('isActive', e.target.checked)}
                        color="primary"
                      />
                    }
                    label="Active Status"
                    sx={{
                      '& .MuiFormControlLabel-label': {
                        fontWeight: 500,
                        color: teacherForm.isActive ? 'success.main' : 'text.secondary',
                      },
                    }}
                  />
                  <Typography variant="caption" color="text.secondary" sx={{ ml: 4, display: 'block' }}>
                    {teacherForm.isActive ? 'Teacher is active and can access the system' : 'Teacher is inactive and cannot access the system'}
                  </Typography>
                </Grid>
              )}
              {dialogType === 'add' && (
                <Grid item xs={12}>
                  <TextField 
                    fullWidth 
                    label="Password" 
                    type="password" 
                    value={teacherForm.password}
                    onChange={(e) => handleFormChange('password', e.target.value)}
                    required
                  />
                </Grid>
              )}
              {(dialogType === 'add' || dialogType === 'edit') && (
                <Grid item xs={12}>
                  <FormControlLabel
                    control={
                      <Switch 
                        checked={teacherForm.canEmailReports}
                        onChange={(e) => handleFormChange('canEmailReports', e.target.checked)}
                      />
                    }
                    label="Allow teacher to email student report directly to parents."
                  />
                </Grid>
              )}
            </Grid>
          )}
        </DialogContent>
        <DialogActions sx={{ p: 3, gap: 2 }}>
          <Button 
            onClick={handleCloseTeacherDialog}
            sx={{
              borderColor: '#d32f2f',
              color: '#d32f2f',
              '&:hover': {
                borderColor: '#b71c1c',
                backgroundColor: '#ffebee',
              },
              '&:active': {
                borderColor: '#c62828',
                backgroundColor: '#ffcdd2',
              },
            }}
          >
            Cancel
          </Button>
          {dialogType !== 'view' && (
            <Button 
              variant="contained" 
              onClick={handleSaveTeacher}
              disabled={!teacherForm.name || !teacherForm.email || !teacherForm.phone || !teacherForm.grade || (dialogType === 'add' && !teacherForm.password)}
              sx={{
                background: brandingGradient,
                '&:hover': {
                  background: brandingGradientHover,
                },
                '&:disabled': {
                  background: 'rgba(0, 0, 0, 0.12)',
                  color: 'rgba(0, 0, 0, 0.38)',
                },
              }}
            >
              {dialogType === 'add' ? 'Add Teacher' : 'Save Changes'}
            </Button>
          )}
        </DialogActions>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog open={openDeleteDialog} onClose={() => setOpenDeleteDialog(false)} maxWidth="sm" fullWidth>
        <DialogTitle
          sx={{
            background: brandingGradient,
            color: 'white',
            fontWeight: 700,
            fontSize: '1.5rem',
            textAlign: 'center',
            py: 3,
            position: 'relative',
            '&::after': {
              content: '""',
              position: 'absolute',
              bottom: 0,
              left: 0,
              right: 0,
              height: '2px',
              background: 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.5) 50%, transparent 100%)',
            }
          }}
        >
          Confirm Delete
        </DialogTitle>
        <DialogContent sx={{ p: 3, pt: '24px !important' }}>
          <Typography variant="body1">
            Are you sure you want to delete {teacherToDelete?.name}? This action cannot be undone.
          </Typography>
        </DialogContent>
        <DialogActions sx={{ p: 3, gap: 2 }}>
          <Button 
            onClick={() => setOpenDeleteDialog(false)}
            sx={{
              borderColor: '#d32f2f',
              color: '#d32f2f',
              '&:hover': {
                borderColor: '#b71c1c',
                backgroundColor: '#ffebee',
              },
              '&:active': {
                borderColor: '#c62828',
                backgroundColor: '#ffcdd2',
              },
            }}
          >
            Cancel
          </Button>
          <Button 
            variant="contained" 
            color="error" 
            onClick={confirmDeleteTeacher}
          >
            Delete
          </Button>
        </DialogActions>
      </Dialog>

      {/* Add Training Resource Dialog */}
      <Dialog open={openTrainingDialog} onClose={() => setOpenTrainingDialog(false)} maxWidth="md" fullWidth>
        <DialogTitle>Add Training Resource</DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12}>
              <TextField fullWidth label="Resource Title" />
            </Grid>
            <Grid item xs={12} md={6}>
              <FormControl fullWidth>
                <InputLabel>Resource Type</InputLabel>
                <Select label="Resource Type">
                  <MenuItem value="video">Video</MenuItem>
                  <MenuItem value="guide">Guide</MenuItem>
                  <MenuItem value="interactive">Interactive Tutorial</MenuItem>
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField fullWidth label="Duration (e.g., 15 min)" />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Description"
                multiline
                rows={3}
                placeholder="Describe what this resource covers..."
              />
            </Grid>
            <Grid item xs={12}>
              <Button variant="outlined" component="label" fullWidth>
                Upload Resource File
                <input type="file" hidden />
              </Button>
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenTrainingDialog(false)}>Cancel</Button>
          <Button variant="contained" onClick={() => setOpenTrainingDialog(false)}>
            Add Resource
          </Button>
        </DialogActions>
      </Dialog>

      {/* Snackbar for notifications */}
      <Snackbar
        open={snackbar.open}
        autoHideDuration={6000}
        onClose={handleCloseSnackbar}
        anchorOrigin={{ vertical: 'top', horizontal: 'center' }}
      >
        <Alert 
          onClose={handleCloseSnackbar} 
          severity={snackbar.severity}
          sx={{ width: '100%' }}
        >
          {snackbar.message}
        </Alert>
      </Snackbar>
    </Container>
  );
};

export default TeacherManagement; 